#pragma once

#define TRACE_CPU_SCOPE_STR( String )	TRACE_CPUPROFILER_EVENT_SCOPE_STR( TEXT( __FUNCTION__ "::" PREPROCESSOR_TO_STRING( __LINE__ ) "::"  String ) )
#define TRACE_CPU_SCOPE					TRACE_CPUPROFILER_EVENT_SCOPE_STR( TEXT( __FUNCTION__ "::" PREPROCESSOR_TO_STRING( __LINE__ ) ) )